source 'https://rubygems.org'

gem 'airborne'
gem 'capybara'
gem 'capybara-screenshot'
gem 'chromedriver-helper'
gem 'cucumber'
gem 'dropbox-sdk'
gem 'faker'
gem 'fuubar'
gem 'pry'
gem 'random-word-generator'
gem 'random_data'
gem 'rspec'
gem 'rspec_html_formatter'
gem 'rubocop'
gem 'selenium-webdriver', '2.53'
